version: '2'
services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=me
      - DOCKER_INFLUXDB_INIT_PASSWORD=arancino
      - DOCKER_INFLUXDB_INIT_ORG=unime
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sensor-token
  grafana:
    image: grafana/grafana:8.0.0
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
#      - ./grafana-provisioning/:/etc/grafana/provisioning
#      - ./grafana-conf/default.ini:/usr/share/grafana/conf/default.ini
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=me
      - GF_SECURITY_ADMIN_PASSWORD=arancino
#      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
#      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
#      - GF_LOG_FILTERS=rendering:debug
#      - GF_INSTALL_PLUGINS=grafana-image-renderer

volumes:
  influxdb-storage:
  grafana-storage:
